React Capstone
K0ppai/dota2_heros pull request #1
Opened 2023-08-01 15:48 UTC by K0ppai

Hello Reviewers 👋😁,
I've worked on the following in this pull request,

1. Build a Home page
    - When the page loads, the webapp shows the list of categories that could be filtered out by search bar.
    - Along with the search input, display some numeric values per category from the API.
    - When the user clicks (or taps) on a category item, the application navigates to the details page.
2. Build a Details page
    - In the details page, the webapp retrieves data from the API to show detailed data
    - When the user clicks on the "Back" button (<), the user navigates to the home page.
3. Write test
    - Create integration tests for application using the React Testing Library.

2023-08-01 17:32 UTC, OyePriscilla requested changes
Hi @K0ppai 👍 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Use React components ✔️ 
Use React props ✔️ 
Handle events in a React app ✔️ 
Used store, actions and reducers in React ✔️ 
Write integration tests with a React testing library ✔️ 

## Required Changes ♻️

- [ ] Please kindly record a video presenting the features of the project as stated in the project requirement. 👍 This will help you to do proper documentation alongside with project develpoment. ℹ️ 

<img width="794" alt="Untitled" src="https://github.com/K0ppai/dota2_heros/assets/103386183/1386ec5e-d11a-4f03-95de-9854a499d180">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 17:32 UTC, OyePriscilla commented on src/components/hero.jsx
> +          />
- [ ] Please kindly ensure that your design is as close to the given template as possible, this will inculcate the habit of reproducing perfectly a given template. I so much believe that recruiters out there watch out for such candidate that pay attention to details. ℹ️ 

- [ ] More so, the UI is not so friendly because the text color is close to the background-color. 👍 

<img width="227" alt="Untitled" src="https://github.com/K0ppai/dota2_heros/assets/103386183/dd0509e9-4ed1-43a3-af51-361aeb797f85">

<img width="396" alt="Untitled" src="https://github.com/K0ppai/dota2_heros/assets/103386183/dd0111ef-ebbc-4ec8-9025-f0b1690dca55">

2023-08-01 17:32 UTC, OyePriscilla commented on src/components/HeroLIst/HerosList.jsx
> +    </div>
- [ ] Please kindly ensure that your design is as close to the given template as possible, this will inculcate the habit of reproducing perfectly a given template. I so much believe that recruiters out there watch out for such candidate that pay attention to details. ℹ️ 

- [ ] Kindly implement the change in color for the alternate items and ensure that the header is spaced properly

<img width="228" alt="Untitled" src="https://github.com/K0ppai/dota2_heros/assets/103386183/09a67ac9-c28a-4c15-bb84-d84cbcc8ec1f">

## Given design
<img width="132" alt="Untitled" src="https://github.com/K0ppai/dota2_heros/assets/103386183/653f1e5d-832d-40cd-8e9d-67eeca5f1597">

2023-08-01 17:32 UTC, OyePriscilla commented on src/components/HeroLIst/HerosList.jsx
> +/* eslint-disable import/no-unresolved */
- [ ] It's not a good practise to disable linters, indly resolve the issues these linters pointed at. Linters are there to catch bug(s) ahead for effective and smooth running of the app. Thanks. ℹ️

2023-08-01 17:32 UTC, OyePriscilla commented on src/pages/Detail.jsx
> +/* eslint-disable react/jsx-one-expression-per-line */
- [ ] It's not a good practise to disable linters, indly resolve the issues these linters pointed at. Linters are there to catch bug(s) ahead for effective and smooth running of the app. Thanks. ℹ️

2023-08-01 17:32 UTC, OyePriscilla commented on src/components/hero.jsx
> +
- [ ] It's not a good practise to disable linters, indly resolve the issues these linters pointed at. Linters are there to catch bug(s) ahead for effective and smooth running of the app. Thanks. ℹ️

2023-08-01 17:32 UTC, OyePriscilla commented on src/App.js
> +
- [ ] It's not a good practise to disable linters, indly resolve the issues these linters pointed at. Linters are there to catch bug(s) ahead for effective and smooth running of the app. Thanks. ℹ️ This [brief tutorial](https://dev.to/haseeb1009/avoid-ignoring-react-hooksexhaustive-deps-linting-warnings-244f) might be of help. 👍

2023-08-01 17:32 UTC, OyePriscilla commented on README.md
> +<!-- SUPPORT -->
- [ ] Please kindly fix this broken link for your README file to be engaging and professional. 👍 

```suggestion
Feel free to check the [issues page](https://github.com/K0ppai/dota2_heros/issues).
```

2023-08-01 17:32 UTC, OyePriscilla commented on README.md
> +
- [ ] Please kindly fix this broken link for your README file to be engaging and professional. 👍 **Perhaps you need to create a LICENSE file or you link it wit MIT.md**

2023-08-02 08:41 UTC, K0ppai commented on src/components/HeroLIst/HerosList.jsx
> +            <Hero key={hero.id} {...hero} data-testid={`hero-${hero.localized_name}`} />
Dear reviewers,
I've disabled eslint for this line. Kindly ignore it, please.

2023-08-02 09:49 UTC, cynthiainga approved these changes
Hi @K0ppai, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [x] Good design ✔️ 
- [x] No linters errors ✔️ 
- [x] Used React props ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 12:32 UTC, merged